POST http://localhost:3001/register
Content-Type: application/json

{
  "username": "adam_richard",
  "name": "Adam Richard",
  "password": "richard_567",
  "gender": "male",
  "location": "Detroit"
}

###

POST http://localhost:3001/login
Content-Type: application/json

{
  "username": "adam_richardd",
  "password": "richard_567"
}